Object {
    "_category": Object {
      "id": 1,
      "name": "Hot Stuff",
    },
    "actors": Array [
      Object {
        "bio": "This is Okoye",
        "id": 1,
        "image": "https://res.cloudinary.com/daf9tr3lf/image/upload/v1/media/profile/actors/actor4_l0oroi",
        "name": "Okoye Adams",
      },
      Object {
        "bio": "This is Susan Cage",
        "id": 3,
        "image": "https://res.cloudinary.com/daf9tr3lf/image/upload/v1/media/profile/actors/actor2_nsru2x",
        "name": "Susan Cage",
      },
    ],
    "date_uploaded": "2023-02-12T16:33:52.714965Z",
    "description": "Desc",
    "desktop_banner": "https://res.cloudinary.com/daf9tr3lf/image/upload/v1/media/banner/womanking_j1xbxq",
    "desktop_thumbnail": "https://res.cloudinary.com/daf9tr3lf/image/upload/v1/media/thumbnail/womanking_slm9ne",
    "genres": Array [
      "Sci-Fi",
      "Comedy",
    ],
    "id": 5,
    "last_modified": "2023-02-12T16:33:52.715013Z",
    "likes": 0,
    "mobile_banner": "https://res.cloudinary.com/daf9tr3lf/image/upload/v1/media/banner/womanking_omwqx0",
    "mobile_thumbnail": "https://res.cloudinary.com/daf9tr3lf/image/upload/v1/media/thumbnail/womanking_mjggco",
    "mood": Array [
      "Happy",
      "Thrilling",
    ],
    "more_like_this": Array [],
    "playlist": 1,
    "published": false,
    "rating": "18+",
    "title": "Woman King",
    "video_link": "EyqI0B4C0D4",
  }
  Object {
    "_category": Object {
      "id": 1,
      "name": "Hot Stuff",
    },
    "actors": Array [
      Object {
        "bio": "This is Okoye",
        "id": 1,
        "image": "https://res.cloudinary.com/daf9tr3lf/image/upload/v1/media/profile/actors/actor4_l0oroi",  
        "name": "Okoye Adams",
      },
      Object {
        "bio": "This is Susan Cage",
        "id": 3,
        "image": "https://res.cloudinary.com/daf9tr3lf/image/upload/v1/media/profile/actors/actor2_nsru2x",  
        "name": "Susan Cage",
      },
    ],
    "date_uploaded": "2023-02-12T16:33:52.714965Z",
    "description": "Desc",
    "desktop_banner": "https://res.cloudinary.com/daf9tr3lf/image/upload/v1/media/banner/womanking_j1xbxq",  
    "desktop_thumbnail": "https://res.cloudinary.com/daf9tr3lf/image/upload/v1/media/thumbnail/womanking_slm9ne",
    "genres": Array [
      "Sci-Fi",
      "Comedy",
    ],
    "id": 5,
    "last_modified": "2023-02-12T16:33:52.715013Z",
    "likes": 0,
    "mobile_banner": "https://res.cloudinary.com/daf9tr3lf/image/upload/v1/media/banner/womanking_omwqx0",   
    "mobile_thumbnail": "https://res.cloudinary.com/daf9tr3lf/image/upload/v1/media/thumbnail/womanking_mjggco",
    "mood": Array [
      "Happy",
      "Thrilling",
    ],
    "more_like_this": Array [],
    "playlist": 1,
    "published": false,
    "rating": "18+",
    "title": "Woman King",
    "video_link": "EyqI0B4C0D4",
  }
  Object {
    "_category": Object {
      "id": 1,
      "name": "Hot Stuff",
    },
    "actors": Array [
      Object {
        "bio": "This is Okoye",
        "id": 1,
        "image": "https://res.cloudinary.com/daf9tr3lf/image/upload/v1/media/profile/actors/actor4_l0oroi",  
        "name": "Okoye Adams",
      },
      Object {
        "bio": "This is Susan Cage",
        "id": 3,
        "image": "https://res.cloudinary.com/daf9tr3lf/image/upload/v1/media/profile/actors/actor2_nsru2x",  
        "name": "Susan Cage",
      },
    ],
    "date_uploaded": "2023-02-12T16:33:52.714965Z",
    "description": "Desc",
    "desktop_banner": "https://res.cloudinary.com/daf9tr3lf/image/upload/v1/media/banner/womanking_j1xbxq",  
    "desktop_thumbnail": "https://res.cloudinary.com/daf9tr3lf/image/upload/v1/media/thumbnail/womanking_slm9ne",
    "genres": Array [
      "Sci-Fi",
      "Comedy",
    ],
    "id": 5,
    "last_modified": "2023-02-12T16:33:52.715013Z",
    "likes": 0,
    "mobile_banner": "https://res.cloudinary.com/daf9tr3lf/image/upload/v1/media/banner/womanking_omwqx0",   
    "mobile_thumbnail": "https://res.cloudinary.com/daf9tr3lf/image/upload/v1/media/thumbnail/womanking_mjggco",
    "mood": Array [
      "Happy",
      "Thrilling",
    ],
    "more_like_this": Array [],
    "playlist": 1,
    "published": false,
    "rating": "18+",
    "title": "Woman King",
    "video_link": "EyqI0B4C0D4",
  }