export { default as Home } from "./Home/Home";
export { default as Login } from "./Auth/Login";
export { default as SignUp } from "./Auth/SignUp"
export { default as VideoScreen } from "./Home/VideoScreen";
export { default as Profile } from "./Profile";
export { default as Lists } from "./Lists";
export { default as Notification } from "./Notification";
export { default as News } from "./News";
export { default as Welcome } from "./Onboard/Welcome";
export { default as ChangeCredentials } from "./ChangeCredentials";
export { default as PasswordReset } from "./PasswordReset";
export { default as VideoEnlongated } from "./VideoEnlongated";
export { default as ActorsProfile } from "./ActorsProfile";
export { default as AccountSettings } from "./AccountSettings";